import data from './firm-data.json';
export const checked='2 October 2026';
export const firms=data;
export type Firm=typeof firms[number];
export const guides = [
 {slug:'drawdown-explained',tag:'THE FUNDAMENTALS',title:'The rule that matters before the profit target.',description:'Understand static, daily and trailing drawdown before choosing a challenge.',paragraphs:['Drawdown defines how much an account may fall before it breaches a rule. The headline percentage is only part of the calculation: the reference balance, equity, time zone and reset method all matter.','A static overall limit stays tied to an initial reference amount. A trailing limit can move as your account reaches new highs. Daily loss may reset at the firm’s server time and can include open-position losses, commissions and swaps.','Compare the exact program and stage. A rule during evaluation may differ from the rule after passing. Follow the official calculation examples and never assume that two 5% limits behave identically.']},
 {slug:'choose-a-challenge',tag:'BEFORE YOU BUY',title:'Compare the program. Not just the price.',description:'A practical checklist for targets, fees, restrictions and payout terms.',paragraphs:['Start with your residency eligibility, the market you trade and the platforms you can use. Then select the exact program, account size and stage you want to compare.','Read every fee: initial evaluation, recurring subscriptions, activation, resets and optional add-ons. A large nominal account size is not cash paid to you, and an evaluation fee can be lost.','Check prohibited strategies, overnight and news rules, consistency rules and withdrawal conditions. Save the terms that apply to your purchase, and confirm material questions with the firm in writing.']},
 {slug:'creator-partnerships',tag:'CREATOR NOTES',title:'Good partnerships start with a clear brief.',description:'Deliverables, disclosures and payment terms deserve the same attention as reach.',paragraphs:['A creator brief should name the audience, campaign goal, platforms, content formats and claims the brand can support. Creators need enough freedom to communicate in their own voice.','Agree the fee, revision allowance, due dates, content usage rights and payment trigger before work begins. Fixed fees and sales bonuses are different commitments and should be written separately.','Disclose the commercial relationship prominently. Report observed results honestly, and separate link clicks from purchases confirmed by the merchant.']},
];
