'use client';
import {PartnerCode} from '@/components/partner-code';
import {useState,useEffect} from 'react';
import Link from '@/components/page-link';
import {ArrowUpRight,ArrowRight,CheckCircle2,Copy,RefreshCw} from 'lucide-react';
import {Table,TableBody,TableRow,TableCell,TableHead,TableHeader} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {firms} from '@/lib/catalogue';
import {Pick,FirmMark} from './site-ui';

export function Comparison(){
 const [market,setMarket]=useState('CFD');const [a,setA]=useState('ftmo');const [b,setB]=useState('the5ers');const [diff,setDiff]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(location.search);const f=firms.find(f=>f.id===q.get('a'));if(f){setMarket(f.market);setA(f.id);const other=firms.find(x=>x.id===q.get('b')&&x.market===f.market&&x.id!==f.id)||firms.find(x=>x.market===f.market&&x.id!==f.id);if(other)setB(other.id);}},[]);
 const options=firms.filter(f=>f.market===market);const first=options.find(f=>f.id===a)||options[0];const second=options.find(f=>f.id===b)||options.find(f=>f.id!==first.id)||first;
 const rows=[['Market',first.market,second.market],['Program',first.plan,second.plan],['PFM rating',first.rating==null?'Not verified':first.rating+' / 5',second.rating==null?'Not verified':second.rating+' / 5'],['PFM review count',String(first.reviewsCount??'Not verified'),String(second.reviewsCount??'Not verified')],['Reported operating years',first.yearsInOperation||'Not verified',second.yearsInOperation||'Not verified'],['Cobalt partnership',first.partner?'Official commercial partner':'No partnership',second.partner?'Official commercial partner':'No partnership'],['Profit targets',first.target,second.target],['Daily loss',first.daily,second.daily],['Overall loss',first.max,second.max],['Minimum days',first.days,second.days],['Important context',first.note,second.note]];
 return <><div className="market-tabs">{['CFD','Futures','Crypto','Stocks'].map(m=><button key={m} className={market===m?'selected':''} onClick={()=>{const fs=firms.filter(f=>f.market===m);setMarket(m);setA(fs[0].id);setB((fs[1]||fs[0]).id)}}>{m}</button>)}</div><div className="compare-selectors"><Pick label="First firm" value={first.id} onChange={setA} options={options.map(f=>({value:f.id,label:f.name}))}/><Pick label="Second firm" value={second.id} onChange={setB} options={options.map(f=>({value:f.id,label:f.name}))}/></div><div className="contact-actions" style={{marginBottom:20}}><label className="consent"><Checkbox checked={diff} onCheckedChange={v=>setDiff(v===true)}/> Show differences only</label><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/compare?a='+first.id+'&b='+second.id);toast.success('Comparison link copied')}catch{toast.error('Copy unavailable')}}}><Copy size={15}/> Share</button></div>{first.id===second.id&&<p className="notice">Choose two different firms to compare.</p>}<div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Rule / program</TableHead>{[first,second].map((f,i)=><TableHead key={i}><FirmMark firm={f}/><strong>{f.name}</strong>{f.partner&&<PartnerCode firmId={f.id}/>}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.filter(r=>!diff||r[1]!==r[2]).map(r=><TableRow key={r[0]}>{r.map((v,i)=><TableCell key={i}>{v}</TableCell>)}</TableRow>)}<TableRow><TableCell>Source and current terms</TableCell>{[first,second].map((f,i)=><TableCell key={i}><a href={`/go/${f.id}`} rel={f.partner?"sponsored":undefined}>Visit firm website ↗</a></TableCell>)}</TableRow></TableBody></Table></div><p className="source-note">Ratings checked 2 October 2026. Original FTMO, The5ers and FundingPips program rules researched 28 September 2026. Verify the exact plan, size, phase and restrictions. Different drawdown definitions are not equivalent.</p></>;
}
export function Calculator(){const [values,setValues]=useState({size:'100000',target:'10',best:'3000',profit:'7000',threshold:'35'});const n=Object.fromEntries(Object.entries(values).map(([k,v])=>[k,Number(v)]));const valid=Object.values(values).every(v=>v.trim()!==''&&Number.isFinite(Number(v)))&&n.size>0&&n.target>=0&&n.best>=0&&n.profit>0&&n.threshold>0&&n.threshold<=100;const minimum=valid?Math.ceil(Math.max(n.best/(n.threshold/100),n.size*n.target/100)*100)/100:0;const money=(v:number)=>v.toLocaleString('en-US',{style:'currency',currency:'USD'});return <div className="split"><div className="panel"><h2>Your scenario</h2><div className="form-grid">{Object.entries({size:'Account size ($)',target:'Evaluation target (%)',best:'Best profitable day ($)',profit:'Current net profit ($)',threshold:'Best-day threshold (%)'}).map(([key,label])=><label className="field" key={key}>{label}<input type="number" step="any" value={values[key as keyof typeof values]} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}</div><p className="help" style={{marginTop:20}}>Calculations stay in your browser. No trading account connection is needed.</p></div><div className="panel" aria-live="polite"><span className="eyebrow">REQUIRED TOTAL NET PROFIT</span>{valid?<><div className="big-result">{money(minimum)}</div><dl className="metric-list"><div><dt>Additional profit needed</dt><dd>{money(Math.max(0,minimum-n.profit))}</dd></div><div><dt>Current best-day ratio</dt><dd>{(n.best/n.profit*100).toFixed(2)}%</dd></div><div><dt>Under this model</dt><dd>{n.profit>=minimum?'Threshold and target met':'More profit required'}</dd></div></dl><p className="help">Required profit is the larger of best-day profit ÷ threshold and your evaluation target. A new larger best day changes this result.</p></>:<p className="error" style={{marginTop:20}}>Enter valid amounts, positive current net profit and a threshold greater than 0% and no more than 100%.</p>}<p className="notice" style={{marginTop:20}}>This is a hypothetical best-day ÷ net-profit model. Firm rules can use different definitions. This result does not establish payout eligibility.</p></div></div>}

