'use client';
import {useState} from 'react';
import {giveawayTemplate,manualGiveawaysSchema,type ManualGiveaway} from '@/lib/manual-giveaway-schema';
const repository='https://github.com/Zabermazz/COBALTSYNDICATE-LANDING-PAGE-/edit/main/lib/manual-giveaways.json';
export function GiveawayBuilder(){
  const [code,setCode]=useState(()=>JSON.stringify([giveawayTemplate()],null,2));const [message,setMessage]=useState('');
  function validate():ManualGiveaway[]|null{try{const parsed=manualGiveawaysSchema.parse(JSON.parse(code));setMessage(`Valid: ${parsed.length} giveaway(s). Download or copy, then commit to GitHub to publish.`);return parsed;}catch(e){setMessage(e instanceof Error?e.message:'Invalid template');return null;}}
  async function copy(){if(!validate())return;try{await navigator.clipboard.writeText(code);setMessage('Copied. Replace the complete GitHub file, then commit the change.');}catch{setMessage('Select the code below and copy it manually.');}}
  function download(){const parsed=validate();if(!parsed)return;const url=URL.createObjectURL(new Blob([JSON.stringify(parsed,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='manual-giveaways.json';a.click();URL.revokeObjectURL(url);}
  function add(){try{const existing=manualGiveawaysSchema.parse(JSON.parse(code));setCode(JSON.stringify([...existing,{...giveawayTemplate(),id:'giveaway-'+crypto.randomUUID()}],null,2));}catch{setMessage('Fix the current template before adding another giveaway.');}}
  return <div className="stack"><section className="panel stack"><h2>Your reusable giveaway template</h2><p>No database or admin token is needed for this publishing method. This editor generates a file; it does not save changes to your website. Only someone with access to your GitHub repository can publish it.</p>
    <ol><li>For your first giveaway, edit the sample below. For later edits, paste the entire current <b>lib/manual-giveaways.json</b> file here first, so existing giveaways are preserved.</li><li>Change the firm, title, account size/type, winner count, dates, rules and task links. Replace the empty entryUrl with your Google Form’s responder link.</li><li>Use <b>Validate</b>, then copy the complete code or download the file.</li><li>Open the GitHub file, replace its contents, and commit. Vercel publishes your change automatically.</li></ol>
    <p className="help">Dates accept a timezone offset. Example: 2026-10-31T21:00:00+05:30 means 31 October at 9 PM India time. Use a unique id for every round. All file contents are public: never include passwords, entry responses or private prize redemption codes.</p>
    <div className="contact-actions"><button className="button" onClick={add}>Add another giveaway</button><a className="text-link" href={repository} target="_blank" rel="noopener noreferrer">Open GitHub file ↗</a></div>
    <label className="field">Giveaway code<textarea aria-label="Giveaway code" spellCheck={false} style={{minHeight:580,fontFamily:'monospace'}} value={code} onChange={e=>setCode(e.target.value)}/></label>
    <div className="contact-actions"><button className="button" onClick={validate}>Validate</button><button className="button" onClick={copy}>Copy code</button><button className="text-link" onClick={download}>Download file</button></div><p role="status" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{message}</p>
  </section><section className="panel stack"><h2>Open, pause or close any round</h2><p><b>draft</b> hides the round. <b>open</b> shows an upcoming countdown until the start, then enables entries. <b>paused</b> stops entry links temporarily. <b>closed</b> stops them permanently for that round. An open round closes automatically at endsAt. Commit each manual status change to publish it.</p><h3>Collect entries and task proof</h3><p>Create a Google Form with name, email, social username and requested proof links. Add a required agreement to your giveaway rules. Paste its responder link into entryUrl. Review the responses manually; the website checklist does not verify follows or select winners.</p><p>The website stops its entry link at the deadline, including on a stale page. Google Forms is separate: close its responses too, and exclude submissions received after your stated deadline. Keep response sheets private.</p><p>This file manages individual rounds, not remaining prize inventory. Create each monthly round with a new id and confirmed dates. No sample giveaway is published automatically.</p></section></div>;
}
