import {session} from '@/lib/education/auth';
import {configured} from '@/lib/education/db';
import {courses,courseData,progress} from '@/lib/education/catalogue';
import {membership} from '@/lib/education/telegram';
import {LearningShell,Hero,s} from '@/components/education/ui';
export const metadata={title:'My learning'};
export default async function Dashboard(){
  let user;try{user=configured()?await session():null;}catch{return <LearningShell><Hero tag="My learning" title="Your learning space"/><p className={s.notice}>Learning services are temporarily unavailable. Please try again shortly.</p></LearningShell>;}
  if(!user)return <LearningShell><Hero tag="My learning" title="Your next chapter starts here."><p>Sign in through our Telegram bot to save your progress and access lessons included with your membership.</p></Hero><div className={s.actions}><a className={s.primary} href="/login">Continue with Telegram →</a><a className={s.secondary} href="/courses">Browse public lessons</a></div></LearningShell>;
  const [items,saved]=await Promise.all([courses(),progress(user.telegram_id)]);let premium=false,unavailable=false;try{premium=await membership(user.telegram_id);}catch{unavailable=true;}
  const data=await Promise.all(items.map(c=>courseData(c.id)));
  return <LearningShell><Hero tag="Your learning dashboard" title={`Welcome back, ${user.first_name}.`}><p>Pick up where you left off. Small, deliberate steps add up.</p></Hero><p className={s.notice}>{unavailable?'Membership verification is temporarily unavailable. Premium lessons are locked until we can verify access.':premium?'Premium membership verified. Your published member lessons are available.':'Premium membership is inactive. Public lessons and your saved progress remain available.'} <a href="/account/membership">View membership →</a></p><div className={s.grid}>{data.filter(d=>d!==null).map(d=>{const done=d.lessons.filter(l=>saved.some(p=>p.lesson_id===l.id&&p.completed_at)).length;const percent=d.lessons.length?Math.round(done/d.lessons.length*100):0;const recent=saved.find(p=>d.lessons.some(l=>l.id===p.lesson_id)&&!p.completed_at);const next=d.lessons.find(l=>l.id===recent?.lesson_id)||d.lessons.find(l=>!saved.some(p=>p.lesson_id===l.id&&p.completed_at))||d.lessons[0];return <article key={d.course.id} className={s.card}><span className={s.badge}>{d.course.level}</span><h2>{d.course.title}</h2><p>{d.lessons.length?`${done} of ${d.lessons.length} lessons completed`:'Lessons coming soon'}</p><progress className={s.progress} value={percent} max={100} aria-label={`${d.course.title}: ${percent}% completed`}/><a className={s.primary} href={next?`/learn/course/${d.course.id}/lesson/${next.slug}`:`/course/${d.course.id}`}>{next?'Continue learning →':'View course'}</a></article>;})}</div></LearningShell>;
}
