'use client';
import {useEffect,useRef,useState} from 'react';
import s from './education.module.css';
export function AuthAction({action,label}:{action:'logout'|'recheck';label:string}) {
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function run(){setBusy(true);setMessage('');try{const r=await fetch(`/api/auth/${action}`,{method:'POST'});const data=await r.json() as {error?:string;premium?:boolean;url:string};if(!r.ok)throw Error(data.error);if(action==='logout')window.location.assign('/courses');else{setMessage(data.premium?'Premium membership verified.':'Premium membership not detected. You can still read public lessons.');}}catch(e){setMessage(e instanceof Error?e.message:'Unable to complete request.');}finally{setBusy(false);}}
  return <div><button className={s.secondary} disabled={busy} onClick={run}>{busy?'Checking…':label}</button><p className={s.result} role="status">{message}</p></div>;
}
export function ClaimLink(){
  const token=useRef(''),captured=useRef(false);const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{if(captured.current)return;captured.current=true;token.current=new URLSearchParams(window.location.hash.slice(1)).get('token')||'';history.replaceState(null,'','/login/claim');},[]);
  async function claim(){setBusy(true);setMessage('Verifying your Telegram membership…');try{const r=await fetch('/api/auth/claim',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token.current})});const data=await r.json() as {error?:string;premium?:boolean;url:string};if(!r.ok)throw Error(data.error);token.current='';window.location.replace('/learn/dashboard');}catch(e){setMessage(e instanceof Error?e.message:'Sign-in unavailable.');setBusy(false);}}
  return <><button className={s.primary} onClick={claim} disabled={busy}>{busy?'Verifying…':'Continue securely →'}</button><p role="status" className={s.result}>{message}</p></>;
}
export function LessonActions({course,lesson,signedIn,completed,hasVideo,hasDownload,initialSeconds}:{course:string;lesson:string;signedIn:boolean;completed:boolean;hasVideo:boolean;hasDownload:boolean;initialSeconds:number}) {
  const [done,setDone]=useState(completed),[message,setMessage]=useState(''),[video,setVideo]=useState(''),[busy,setBusy]=useState(false);const lastSaved=useRef(0),position=useRef(initialSeconds);
  async function save(complete=false,seconds=position.current){if(!signedIn)return;try{const r=await fetch('/api/learn/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({course,lesson,complete,seconds})});if(!r.ok)throw Error();if(complete){setDone(true);setMessage('Lesson marked complete. Your progress is saved.');}}catch{setMessage('Progress could not be saved. Check your connection or membership and try again.');}}
  useEffect(()=>{if(signedIn){void fetch('/api/learn/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({course,lesson,seconds:0,complete:false})}).catch(()=>{});}},[course,lesson,signedIn]);
  async function asset(kind:'video'|'download'){setBusy(true);setMessage('');try{const r=await fetch('/api/learn/asset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({course,lesson,kind})});const data=await r.json() as {error?:string;premium?:boolean;url:string};if(!r.ok)throw Error(data.error);if(kind==='video')setVideo(data.url);else{const a=document.createElement('a');a.href=data.url;a.target='_blank';a.rel='noopener noreferrer';a.click();}}catch(e){setMessage(e instanceof Error?e.message:'Asset unavailable.');}finally{setBusy(false);}}
  return <div>{hasVideo&&<><button className={s.primary} onClick={()=>asset('video')} disabled={busy}>{video?'Refresh video access':'Load lesson video'}</button>{video&&<video className={s.video} controls preload="metadata" src={video} onLoadedMetadata={e=>{e.currentTarget.currentTime=Math.min(position.current,e.currentTarget.duration||0);}} onTimeUpdate={e=>{position.current=Math.floor(e.currentTarget.currentTime);if(Date.now()-lastSaved.current>30000){lastSaved.current=Date.now();void save();}}} onPause={()=>void save()} onEnded={()=>void save(true)} onError={()=>setMessage('Video access may have expired. Use “Refresh video access” to try again.')} controlsList="nodownload"/>}</>}
  <div className={s.actions}>{hasDownload&&<button className={s.secondary} onClick={()=>asset('download')} disabled={busy}>Open lesson resource ↗</button>}{signedIn?<button className={s.secondary} onClick={()=>void save(true)} disabled={done}>{done?'✓ Lesson completed':'Mark as complete'}</button>:<a className={s.secondary} href="/login">Sign in to save progress</a>}</div><p role="status" className={s.result}>{message}</p></div>;
}
