'use client';
import {useState} from 'react';
import s from './education.module.css';
const template={id:'new-course',title:'New course',summary:'Describe the learning outcomes.',level:'beginner',access:'public',published:false,position:4,sections:[{id:'new-course-section-one',title:'Getting started',position:1,lessons:[{id:'new-course-introduction',slug:'introduction',title:'Introduction',summary:'What you will learn.',access:null,published:false,position:1,duration_seconds:0,body:'Write your lesson here. Separate paragraphs with a blank line.',video_path:null,download_path:null}]}]};
export function CourseEditor(){const [token,setToken]=useState(''),[items,setItems]=useState<{id:string;title:string;published:boolean}[]>([]),[value,setValue]=useState(JSON.stringify(template,null,2)),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function request(path:string,init:RequestInit={}){const r=await fetch('/api/admin/courses'+path,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}});const raw=await r.text();let data;try{data=JSON.parse(raw);}catch{throw Error(raw);}if(!r.ok)throw Error(data.error||'Request failed');return data;}
 async function run(task:()=>Promise<void>){setBusy(true);setMessage('');try{await task();}catch(e){setMessage(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 return <><p className={s.notice}>Team-only editor. The admin key is held in this page’s memory and is cleared when you leave. Course content is never loaded before the key is verified.</p><label className={s.label}>Existing website admin key<input className={s.input} type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><div className={s.actions}><button className={s.primary} disabled={busy||!token} onClick={()=>run(async()=>{setItems(await request(''));setMessage('Courses loaded.');})}>Load courses</button><button className={s.secondary} onClick={()=>{setValue(JSON.stringify(template,null,2));setMessage('New draft template loaded. Give it unique IDs before saving.');}}>New draft</button></div><div className={s.actions}>{items.map(c=><button className={s.secondary} key={c.id} disabled={busy} onClick={()=>run(async()=>setValue(JSON.stringify(await request('?id='+encodeURIComponent(c.id)),null,2)))}>{c.title} · {c.published?'Published':'Draft'}</button>)}</div><div className={s.adminHelp}><h2>Edit course content</h2><p>Change the fields below. Set <strong>published</strong> to true on the course and the lessons you want to release. Access can be <strong>public</strong>, <strong>free_member</strong> or <strong>premium</strong>; a lesson’s null access inherits its course. Keep IDs unchanged when updating existing lessons so progress is preserved.</p><p>Upload private videos/PDFs to the Supabase <strong>course-assets</strong> bucket, then enter their relative paths. Never paste a public video URL. To remove a lesson from the catalogue, set its published field to false; omitting it from this editor does not delete it.</p></div><label className={s.label}>Course configuration<textarea className={`${s.input} ${s.editor}`} spellCheck={false} value={value} onChange={e=>setValue(e.target.value)}/></label><button className={s.primary} disabled={busy||!token} onClick={()=>run(async()=>{JSON.parse(value);await request('',{method:'POST',body:value});setItems(await request(''));setMessage('Saved. Published content is now available on the website.');})}>{busy?'Working…':'Save course'}</button><p className={s.result} role="status">{message}</p></>;
}
